version: '3.8'

services:
  python-api:
    build:
      context: .
      dockerfile: employee_app/Dockerfile
    ports:
      - "8080:8080"

  spring-backend:
    build: ./manager_app
    ports:
      - "9090:9090"
    restart: always

  web-frontend:
    build: ./web_app
    ports:
      - "5173:5173"
    depends_on:
      - python-api
      - spring-backend
    restart: always